name: CI
on:
  push:
  pull_request:

env:
  SECRET_KEY: "some-secret-key"
  DEBUG: "False"

  POSTGRES_DB: rewards
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    services:
      db:
        image: postgres:18
        env:
          POSTGRES_DB: rewards
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Install requirements"
        run: pip install -r requirements.txt

      - name: "Migrate"
        run: python manage.py migrate

      - name: "Run tests"
        run: python manage.py test
